# Portions Copyright (c) Microsoft Corporation
# Licensed under the Apache License, Version 2.0. See LICENSE file in the project root for full license information.
# Changes: TLS setting

name: media-mongodb

ports:
  - port: 27017
    targetPort: 27017

container:
  args: 
  - --config
  - /social-network-microservices/config/mongod.conf
  image: library/mongo
  imageVersion: 4.4.6
  name: media-mongodb
  ports: 
  - containerPort: 27017

configMaps:
  - name: mongod.conf
    mountPath: /social-network-microservices/config/mongod.conf
    value: mongod

tls:
  mode: disabled
  certificateKeyFile: ""
  CAFile: ""